name: ğŸš€ DÃ©ploiement FTP

on:
  push:
    branches:
      - main  # Le dÃ©ploiement se lance quand vous envoyez du code sur 'main'

jobs:
  web-deploy:
    name: Build et Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš RÃ©cupÃ©rer le code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Build du projet
        run: |
          npm install
          npm run build

      - name: ğŸ“‚ Envoi via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /home/quarksydigital.com/