name: ğŸš€ DÃ©ploiement FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build et Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš RÃ©cupÃ©rer le code
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Build du projet (Vite)
        run: |
          npm install
          npm run build

      - name: ğŸ“‚ Envoi via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          # Assurez-vous que ce chemin est le bon sur votre serveur FTP
          server-dir: /home/quarksydigital.com/
          # Optionnel : supprime les fichiers sur le serveur qui ne sont pas dans dist
          delete-destination: false