# Utilisez 'dist' car c'est le dossier que crée votre projet (vu sur vos images)
          local-dir: ./dist/
          
          # L'adresse COMPLÈTE de votre dossier public sur Spaceship
          server-dir: /home/rzpvmoglsd/public_html/
